# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12064e705641b5b62d3775ced5fd8a334af52273c8be3c20a986eb4e1488937189c1a67a463167f38cf90639613c806920c80b325c07230a99c8f43c133889cd

test:
  secret_key_base: c3a8d244408bd46917db20935ed108028efaa47df5726916b87be92b697e71daaccff1c124136e3e907c15ed747ee0007b69d274faa98e7b1a5bc0dba7d90c26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
