require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HomePageBlocksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # HomePageBlock. As you add validations to HomePageBlock, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HomePageBlocksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all home_page_blocks as @home_page_blocks" do
      home_page_block = HomePageBlock.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:home_page_blocks)).to eq([home_page_block])
    end
  end

  describe "GET #show" do
    it "assigns the requested home_page_block as @home_page_block" do
      home_page_block = HomePageBlock.create! valid_attributes
      get :show, {:id => home_page_block.to_param}, valid_session
      expect(assigns(:home_page_block)).to eq(home_page_block)
    end
  end

  describe "GET #new" do
    it "assigns a new home_page_block as @home_page_block" do
      get :new, {}, valid_session
      expect(assigns(:home_page_block)).to be_a_new(HomePageBlock)
    end
  end

  describe "GET #edit" do
    it "assigns the requested home_page_block as @home_page_block" do
      home_page_block = HomePageBlock.create! valid_attributes
      get :edit, {:id => home_page_block.to_param}, valid_session
      expect(assigns(:home_page_block)).to eq(home_page_block)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new HomePageBlock" do
        expect {
          post :create, {:home_page_block => valid_attributes}, valid_session
        }.to change(HomePageBlock, :count).by(1)
      end

      it "assigns a newly created home_page_block as @home_page_block" do
        post :create, {:home_page_block => valid_attributes}, valid_session
        expect(assigns(:home_page_block)).to be_a(HomePageBlock)
        expect(assigns(:home_page_block)).to be_persisted
      end

      it "redirects to the created home_page_block" do
        post :create, {:home_page_block => valid_attributes}, valid_session
        expect(response).to redirect_to(HomePageBlock.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved home_page_block as @home_page_block" do
        post :create, {:home_page_block => invalid_attributes}, valid_session
        expect(assigns(:home_page_block)).to be_a_new(HomePageBlock)
      end

      it "re-renders the 'new' template" do
        post :create, {:home_page_block => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested home_page_block" do
        home_page_block = HomePageBlock.create! valid_attributes
        put :update, {:id => home_page_block.to_param, :home_page_block => new_attributes}, valid_session
        home_page_block.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested home_page_block as @home_page_block" do
        home_page_block = HomePageBlock.create! valid_attributes
        put :update, {:id => home_page_block.to_param, :home_page_block => valid_attributes}, valid_session
        expect(assigns(:home_page_block)).to eq(home_page_block)
      end

      it "redirects to the home_page_block" do
        home_page_block = HomePageBlock.create! valid_attributes
        put :update, {:id => home_page_block.to_param, :home_page_block => valid_attributes}, valid_session
        expect(response).to redirect_to(home_page_block)
      end
    end

    context "with invalid params" do
      it "assigns the home_page_block as @home_page_block" do
        home_page_block = HomePageBlock.create! valid_attributes
        put :update, {:id => home_page_block.to_param, :home_page_block => invalid_attributes}, valid_session
        expect(assigns(:home_page_block)).to eq(home_page_block)
      end

      it "re-renders the 'edit' template" do
        home_page_block = HomePageBlock.create! valid_attributes
        put :update, {:id => home_page_block.to_param, :home_page_block => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested home_page_block" do
      home_page_block = HomePageBlock.create! valid_attributes
      expect {
        delete :destroy, {:id => home_page_block.to_param}, valid_session
      }.to change(HomePageBlock, :count).by(-1)
    end

    it "redirects to the home_page_blocks list" do
      home_page_block = HomePageBlock.create! valid_attributes
      delete :destroy, {:id => home_page_block.to_param}, valid_session
      expect(response).to redirect_to(home_page_blocks_url)
    end
  end

end
